### ISSUE TITLE
I made these mistakes, how can I resolve them?

### ISSUE THREAD

**Issue by yamanacn** [jbilcke-hf/FacePoke#1]
^
2024-10-05 18:42:15,261 - aiohttp.access - INFO - ::1 [05/Oct/2024:18:42:15 +0800] "UNKNOWN / HTTP/1.0" 400 248 "-" "-"
2024-10-05 18:42:46,239 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "E:\facepoke\FacePoke\env\lib\site-packages\aiohttp\web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    bytearray(b'\x16\x03\x01\x06\xc6\x01')
                 ^
2024-10-05 18:42:46,240 - aiohttp.access - INFO - ::1 [05/Oct/2024:18:42:46 +0800] "UNKNOWN / HTTP/1.0" 400 248 "-" "-"
2024-10-05 18:42:46,252 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "E:\facepoke\FacePoke\env\lib\site-packages\aiohttp\web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    bytearray(b'\x16\x03\x01\x06\xa6\x01')
                 ^
2024-10-05 18:42:46,253 - aiohttp.access - INFO - ::1 [05/Oct/2024:18:42:46 +0800] "UNKNOWN / HTTP/1.0" 400 248 "-" "-"

**Comment by ext452** [comment]
Same here. After running server and opened http://localhost:8080 in my web browser, I have same errors.

**Comment by jbilcke-hf** [comment]
Hello,

can you share some details about your system?

Right now the app has only been tested for its demonstration environment which is a Hugging Face Space (Docker + Linux + + a GPU + CUDA 12)

**Comment by ext452** [comment]
Changing to 'ws' from 'wss' resolve a problem (client/src/lib/facePoke.ts)
this.ws = new WebSocket(`ws://${window.location.host}/ws`);

**Comment by yamanacn** [comment]
> Changing to 'ws' from 'wss' resolve a problem (client/src/lib/facePoke.ts)从 'wss' 更改为 'ws' 解决了一个问题（client/src/lib/facePoke.ts） this.ws = new WebSocket(`ws://${window.location.host}/ws`);this.ws = new WebSocket( `ws://${window.location.host}/ws` );

I will try it through your method.

**Comment by Neltherion** [comment]
This solved my problem!

**Comment by rltgjqdydid** [comment]
Same here, I changed wss to ws, but it didn't fix the issue.

**Comment by Preises** [comment]
Same, changed it, got this.


2024-10-06 17:34:03,933 - aiohttp.access - INFO - 127.0.0.1 [06/Oct/2024:16:34:03 +0100] "UNKNOWN / HTTP/1.0" 400 248 "-" "-"
2024-10-06 17:34:33,942 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "C:\Users\J\venv310\lib\site-packages\aiohttp\web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    bytearray(b'\x16\x03\x01\x02\x8c\x01')

**Comment by Pbugyon** [comment]
> Changing to 'ws' from 'wss' resolve a problem (client/src/lib/facePoke.ts) this.ws = new WebSocket(`ws://${window.location.host}/ws`);

won't work for me;
2024-10-06 18:43:07,674 - __main__ - DEBUG - Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
2024-10-06 18:43:09,256 - loader - INFO - 🚀 Setting up storage directories...
2024-10-06 18:43:09,256 - loader - INFO -   Directory already exists: /tmp/data\models
2024-10-06 18:43:09,256 - loader - INFO - ✅ Storage directories setup completed.
2024-10-06 18:43:09,422 - __main__ - INFO - Starting FacePoke application
2024-10-06 18:43:09,422 - asyncio - DEBUG - Using proactor: IocpProactor
2024-10-06 18:43:09,427 - __main__ - INFO - Initializing application...
2024-10-06 18:43:09,427 - loader - INFO - 🚀 Starting model initialization...
2024-10-06 18:43:09,427 - loader - INFO -   🔎 Looking for models...
2024-10-06 18:43:09,427 - loader - DEBUG -     ✅ dwpose/dw-ll_ucoco_384.pth
2024-10-06 18:43:09,427 - loader - DEBUG -     ✅ face-detector/s3fd-619a316812.pth
2024-10-06 18:43:09,427 - loader - DEBUG -     ✅ liveportrait/spade_generator.pth
2024-10-06 18:43:09,427 - loader - DEBUG -     ✅ liveportrait/warping_module.pth
2024-10-06 18:43:09,427 - loader - DEBUG -     ✅ liveportrait/motion_extractor.pth
2024-10-06 18:43:09,427 - loader - DEBUG -     ✅ liveportrait/stitching_retargeting_module.pth
2024-10-06 18:43:09,427 - loader - DEBUG -     ✅ liveportrait/appearance_feature_extractor.pth
2024-10-06 18:43:09,427 - loader - DEBUG -     ✅ liveportrait/landmark.onnx
2024-10-06 18:43:09,427 - loader - DEBUG -     ✅ insightface/models/buffalo_l.zip
2024-10-06 18:43:09,427 - loader - DEBUG -     ✅ insightface/buffalo_l/det_10g.onnx
2024-10-06 18:43:09,427 - loader - DEBUG -     ✅ insightface/buffalo_l/2d106det.onnx
2024-10-06 18:43:09,427 - loader - DEBUG -     ✅ sd-vae-ft-mse/diffusion_pytorch_model.bin
2024-10-06 18:43:09,427 - loader - DEBUG -     ✅ sd-vae-ft-mse/diffusion_pytorch_model.safetensors
2024-10-06 18:43:09,427 - loader - DEBUG -     ✅ sd-vae-ft-mse/config.json
2024-10-06 18:43:09,427 - loader - INFO -   ✅ All models are available
2024-10-06 18:43:10,012 - httpx - DEBUG - load_ssl_context verify=True cert=None trust_env=True http2=False
2024-10-06 18:43:10,012 - httpx - DEBUG - load_verify_locations cafile='C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\certifi\\cacert.pem'
2024-10-06 18:43:10,017 - httpx - DEBUG - load_ssl_context verify=True cert=None trust_env=True http2=False
2024-10-06 18:43:10,022 - httpx - DEBUG - load_verify_locations cafile='C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\certifi\\cacert.pem'
2024-10-06 18:43:10,091 - httpx - DEBUG - load_ssl_context verify=True cert=None trust_env=True http2=False
2024-10-06 18:43:10,096 - httpx - DEBUG - load_verify_locations cafile='C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\certifi\\cacert.pem'
2024-10-06 18:43:10,102 - httpx - DEBUG - load_ssl_context verify=True cert=None trust_env=True http2=False
2024-10-06 18:43:10,102 - httpx - DEBUG - load_verify_locations cafile='C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\certifi\\cacert.pem'
2024-10-06 18:43:10,112 - httpx - DEBUG - load_ssl_context verify=True cert=None trust_env=True http2=False
2024-10-06 18:43:10,112 - httpx - DEBUG - load_verify_locations cafile='C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\certifi\\cacert.pem'
2024-10-06 18:43:10,122 - httpcore.connection - DEBUG - connect_tcp.started host='api.gradio.app' port=443 local_address=None timeout=3 socket_options=None
2024-10-06 18:43:10,194 - PIL.Image - DEBUG - Importing BlpImagePlugin
2024-10-06 18:43:10,200 - PIL.Image - DEBUG - Importing BmpImagePlugin
2024-10-06 18:43:10,200 - PIL.Image - DEBUG - Importing BufrStubImagePlugin
2024-10-06 18:43:10,200 - PIL.Image - DEBUG - Importing CurImagePlugin
2024-10-06 18:43:10,200 - PIL.Image - DEBUG - Importing DcxImagePlugin
2024-10-06 18:43:10,200 - PIL.Image - DEBUG - Importing DdsImagePlugin
2024-10-06 18:43:10,200 - PIL.Image - DEBUG - Importing EpsImagePlugin
2024-10-06 18:43:10,205 - PIL.Image - DEBUG - Importing FitsImagePlugin
2024-10-06 18:43:10,205 - PIL.Image - DEBUG - Importing FliImagePlugin
2024-10-06 18:43:10,205 - PIL.Image - DEBUG - Importing FpxImagePlugin
2024-10-06 18:43:10,205 - PIL.Image - DEBUG - Image: failed to import FpxImagePlugin: No module named 'olefile'
2024-10-06 18:43:10,205 - PIL.Image - DEBUG - Importing FtexImagePlugin
2024-10-06 18:43:10,205 - PIL.Image - DEBUG - Importing GbrImagePlugin
2024-10-06 18:43:10,205 - PIL.Image - DEBUG - Importing GifImagePlugin
2024-10-06 18:43:10,209 - PIL.Image - DEBUG - Importing GribStubImagePlugin
2024-10-06 18:43:10,210 - PIL.Image - DEBUG - Importing Hdf5StubImagePlugin
2024-10-06 18:43:10,210 - PIL.Image - DEBUG - Importing IcnsImagePlugin
2024-10-06 18:43:10,210 - PIL.Image - DEBUG - Importing IcoImagePlugin
2024-10-06 18:43:10,210 - PIL.Image - DEBUG - Importing ImImagePlugin
2024-10-06 18:43:10,210 - PIL.Image - DEBUG - Importing ImtImagePlugin
2024-10-06 18:43:10,210 - PIL.Image - DEBUG - Importing IptcImagePlugin
2024-10-06 18:43:10,210 - PIL.Image - DEBUG - Importing JpegImagePlugin
2024-10-06 18:43:10,210 - PIL.Image - DEBUG - Importing Jpeg2KImagePlugin
2024-10-06 18:43:10,210 - PIL.Image - DEBUG - Importing McIdasImagePlugin
2024-10-06 18:43:10,215 - PIL.Image - DEBUG - Importing MicImagePlugin
2024-10-06 18:43:10,215 - PIL.Image - DEBUG - Image: failed to import MicImagePlugin: No module named 'olefile'
2024-10-06 18:43:10,215 - PIL.Image - DEBUG - Importing MpegImagePlugin
2024-10-06 18:43:10,215 - PIL.Image - DEBUG - Importing MpoImagePlugin
2024-10-06 18:43:10,215 - PIL.Image - DEBUG - Importing MspImagePlugin
2024-10-06 18:43:10,215 - PIL.Image - DEBUG - Importing PalmImagePlugin
2024-10-06 18:43:10,221 - PIL.Image - DEBUG - Importing PcdImagePlugin
2024-10-06 18:43:10,221 - PIL.Image - DEBUG - Importing PcxImagePlugin
2024-10-06 18:43:10,221 - PIL.Image - DEBUG - Importing PdfImagePlugin
2024-10-06 18:43:10,226 - PIL.Image - DEBUG - Importing PixarImagePlugin
2024-10-06 18:43:10,226 - PIL.Image - DEBUG - Importing PngImagePlugin
2024-10-06 18:43:10,226 - PIL.Image - DEBUG - Importing PpmImagePlugin
2024-10-06 18:43:10,226 - PIL.Image - DEBUG - Importing PsdImagePlugin
2024-10-06 18:43:10,226 - PIL.Image - DEBUG - Importing QoiImagePlugin
2024-10-06 18:43:10,226 - PIL.Image - DEBUG - Importing SgiImagePlugin
2024-10-06 18:43:10,226 - PIL.Image - DEBUG - Importing SpiderImagePlugin
2024-10-06 18:43:10,226 - PIL.Image - DEBUG - Importing SunImagePlugin
2024-10-06 18:43:10,226 - PIL.Image - DEBUG - Importing TgaImagePlugin
2024-10-06 18:43:10,226 - PIL.Image - DEBUG - Importing TiffImagePlugin
2024-10-06 18:43:10,226 - PIL.Image - DEBUG - Importing WebPImagePlugin
2024-10-06 18:43:10,231 - PIL.Image - DEBUG - Importing WmfImagePlugin
2024-10-06 18:43:10,231 - PIL.Image - DEBUG - Importing XbmImagePlugin
2024-10-06 18:43:10,231 - PIL.Image - DEBUG - Importing XpmImagePlugin
2024-10-06 18:43:10,231 - PIL.Image - DEBUG - Importing XVThumbImagePlugin
2024-10-06 18:43:10,346 - httpcore.connection - DEBUG - connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x0000020ECB1EC6A0>
2024-10-06 18:43:10,351 - httpcore.connection - DEBUG - start_tls.started ssl_context=<ssl.SSLContext object at 0x0000020ECA1674C0> server_hostname='api.gradio.app' timeout=3
2024-10-06 18:43:10,738 - httpcore.connection - DEBUG - start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x0000020ECB1EC670>
2024-10-06 18:43:10,738 - httpcore.http11 - DEBUG - send_request_headers.started request=<Request [b'GET']>
2024-10-06 18:43:10,738 - httpcore.http11 - DEBUG - send_request_headers.complete
2024-10-06 18:43:10,738 - httpcore.http11 - DEBUG - send_request_body.started request=<Request [b'GET']>
2024-10-06 18:43:10,738 - httpcore.http11 - DEBUG - send_request_body.complete
2024-10-06 18:43:10,738 - httpcore.http11 - DEBUG - receive_response_headers.started request=<Request [b'GET']>
2024-10-06 18:43:10,937 - httpcore.http11 - DEBUG - receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Date', b'Sun, 06 Oct 2024 16:43:17 GMT'), (b'Content-Type', b'application/json'), (b'Content-Length', b'3'), (b'Connection', b'keep-alive'), (b'Server', b'nginx/1.18.0'), (b'Access-Control-Allow-Origin', b'*')])
2024-10-06 18:43:10,937 - httpx - INFO - HTTP Request: GET https://api.gradio.app/gradio-messaging/en "HTTP/1.1 200 OK"
2024-10-06 18:43:10,942 - httpcore.http11 - DEBUG - receive_response_body.started request=<Request [b'GET']>
2024-10-06 18:43:10,942 - httpcore.http11 - DEBUG - receive_response_body.complete
2024-10-06 18:43:10,942 - httpcore.http11 - DEBUG - response_closed.started
2024-10-06 18:43:10,942 - httpcore.http11 - DEBUG - response_closed.complete
2024-10-06 18:43:10,942 - httpcore.connection - DEBUG - close.started
2024-10-06 18:43:10,942 - httpcore.connection - DEBUG - close.complete
C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\transport.py:258: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,
2024-10-06 18:43:12,177 - loader - INFO -   ⏳ Loading LivePortrait models...
2024-10-06 18:43:17,834 - loader - INFO -   ✅ LivePortrait models loaded successfully.
2024-10-06 18:43:17,834 - loader - INFO - ✅ Model initialization completed.
2024-10-06 18:43:17,834 - __main__ - INFO - 🚀 Creating Engine instance...
2024-10-06 18:43:17,834 - engine - INFO - ✅ FacePoke Engine initialized successfully.
2024-10-06 18:43:17,834 - __main__ - INFO - ✅ Engine instance created.
2024-10-06 18:43:17,834 - __main__ - INFO - Application routes configured
2024-10-06 18:43:17,834 - __main__ - INFO - Application initialized, starting web server
2024-10-06 18:43:17,834 - asyncio - DEBUG - Using proactor: IocpProactor
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
2024-10-06 18:43:23,504 - aiohttp.access - INFO - 127.0.0.1 [06/Oct/2024:17:43:23 +0100] "GET / HTTP/1.1" 200 488 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
2024-10-06 18:43:23,524 - aiohttp.access - INFO - 127.0.0.1 [06/Oct/2024:17:43:23 +0100] "GET /index.js HTTP/1.1" 200 1295165 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
2024-10-06 18:43:23,658 - aiohttp.access - INFO - 127.0.0.1 [06/Oct/2024:17:43:23 +0100] "GET /hf-logo.svg HTTP/1.1" 200 4792 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
2024-10-06 18:43:23,950 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    bytearray(b'\x16\x03\x01\x06\xa6\x01')
                 ^
2024-10-06 18:43:23,951 - aiohttp.access - INFO - 127.0.0.1 [06/Oct/2024:17:43:23 +0100] "UNKNOWN / HTTP/1.0" 400 248 "-" "-"
2024-10-06 18:43:24,259 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    bytearray(b'\x16\x03\x01\x06\xe6\x01')
                 ^
2024-10-06 18:43:24,260 - aiohttp.access - INFO - 127.0.0.1 [06/Oct/2024:17:43:24 +0100] "UNKNOWN / HTTP/1.0" 400 248 "-" "-"
2024-10-06 18:43:26,576 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    bytearray(b'\x16\x03\x01\x06\xa6\x01')
                 ^
2024-10-06 18:43:26,577 - aiohttp.access - INFO - 127.0.0.1 [06/Oct/2024:17:43:26 +0100] "UNKNOWN / HTTP/1.0" 400 248 "-" "-"
2024-10-06 18:43:26,884 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    bytearray(b'\x16\x03\x01\x06\xe6\x01')
                 ^
2024-10-06 18:43:26,885 - aiohttp.access - INFO - 127.0.0.1 [06/Oct/2024:17:43:26 +0100] "UNKNOWN / HTTP/1.0" 400 248 "-" "-"
2024-10-06 18:43:31,480 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    bytearray(b'\x16\x03\x01\x06\xe6\x01')
                 ^
2024-10-06 18:43:31,481 - aiohttp.access - INFO - 127.0.0.1 [06/Oct/2024:17:43:31 +0100] "UNKNOWN / HTTP/1.0" 400 248 "-" "-"
2024-10-06 18:43:31,788 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    bytearray(b'\x16\x03\x01\x06\xa6\x01')
                 ^
2024-10-06 18:43:31,788 - aiohttp.access - INFO - 127.0.0.1 [06/Oct/2024:17:43:31 +0100] "UNKNOWN / HTTP/1.0" 400 248 "-" "-"

**Comment by stevanisya** [comment]
hello, 
I got the same problem. If anyone got a solution for this ?

**Comment by Pbugyon** [comment]
i did it, i'm basically a bit stupid so i didn't repeat the bun command again to the modified code, also the correct code is " 

> this.ws = new WebSocket(`ws://${window.location.host}/ws`);

 " after modifying the code save, use the terminal and run the command: " bun build ./src/index.tsx --outdir ../public/ ". then you are ready

**Comment by nicknamerequired** [comment]
@Pbugyon with the bun command, it works. Thanks a lot.

**Comment by dborup** [comment]
@Pbugyon thanks, it works.

**Comment by TigerFox57** [comment]
> i did it, i'm basically a bit stupid so i didn't repeat the bun command again to the modified code, also the correct code is
> 
> ```
> this.ws = new WebSocket(`ws://${window.location.host}/ws`);

Just popping in to say that this fixed my issue. Thanks.

**Comment by destromestro** [comment]
> Same here, I changed wss to ws, but it didn't fix the issue.

after you fix it you have to go to the main Facepoke folder, run this command in the terminal  bun build ./src/index.tsx --outdir ../public/. 

Then it worked for me
