### ISSUE TITLE
BadStatusLine 400, Invalid method encountered

### ISSUE THREAD

**Issue by androdlang** [jbilcke-hf/FacePoke#11]
changed the browser from FF to Chrome, but in both the same error (WIN10) as soon I started the client:

2024-10-09 07:17:11,546 - loader - INFO - 🚀 Setting up storage directories...
2024-10-09 07:17:11,546 - loader - INFO -   Directory already exists: /tmp/data\models
2024-10-09 07:17:11,547 - loader - INFO - ✅ Storage directories setup completed.
2024-10-09 07:17:12,353 - __main__ - INFO - Starting FacePoke application
2024-10-09 07:17:12,355 - __main__ - INFO - Initializing application...
2024-10-09 07:17:12,355 - loader - INFO - 🚀 Starting model initialization...
2024-10-09 07:17:12,356 - loader - INFO -   🔎 Looking for models...
2024-10-09 07:17:12,363 - loader - INFO -   ✅ All models are available
2024-10-09 07:17:18,643 - httpx - INFO - HTTP Request: GET https://api.gradio.app/gradio-messaging/en "HTTP/1.1 200 OK"
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
2024-10-09 07:17:45,047 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "C:\path\\.conda\envs\FacePoke\lib\site-packages\aiohttp\web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    bytearray(b'\x16\x03\x01\x01\x0f\x01')
                 ^

**Comment by dotNet-Spider** [comment]
This is the same issue as https://github.com/jbilcke-hf/FacePoke/issues/6

**Comment by androdlang** [comment]
@dotNet-Spider Thank you, confirmed, solution is in this line "this.ws = new WebSocket(`ws://${window.location.host}/ws`);".
Solved!

**Comment by androdlang** [comment]
Solved
