### ISSUE TITLE
about "docker install"Error during application initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

### ISSUE THREAD

**Issue by tiandaoyuxi** [jbilcke-hf/FacePoke#12]
D:\FacePoke>docker run -p 8080:8080 facepoke

==========
== CUDA ==
==========

CUDA Version 12.4.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .

2024-10-09 05:31:51,658 - loader - INFO - 🚀 Setting up storage directories...
2024-10-09 05:31:51,658 - loader - INFO -   Directory created: /tmp/data/models
2024-10-09 05:31:51,658 - loader - INFO - ✅ Storage directories setup completed.
2024-10-09 05:31:51,746 - __main__ - INFO - Starting FacePoke application
2024-10-09 05:31:51,746 - __main__ - INFO - Initializing application...
2024-10-09 05:31:51,746 - loader - INFO - 🚀 Starting model initialization...
2024-10-09 05:31:51,746 - loader - INFO -   🔎 Looking for models...
2024-10-09 05:31:51,746 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/dwpose/dw-ll_ucoco_384.pth
2024-10-09 05:31:51,747 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/face-detector/s3fd-619a316812.pth
2024-10-09 05:31:51,747 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/liveportrait/spade_generator.pth
2024-10-09 05:31:51,748 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/liveportrait/warping_module.pth
2024-10-09 05:31:51,749 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/liveportrait/motion_extractor.pth
2024-10-09 05:31:51,750 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/liveportrait/stitching_retargeting_module.pth
2024-10-09 05:31:51,752 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/liveportrait/appearance_feature_extractor.pth
2024-10-09 05:31:51,754 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/liveportrait/landmark.onnx
2024-10-09 05:31:51,756 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/insightface/models/buffalo_l.zip
2024-10-09 05:31:51,756 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/insightface/buffalo_l/det_10g.onnx
2024-10-09 05:31:51,757 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/insightface/buffalo_l/2d106det.onnx
2024-10-09 05:31:51,757 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/sd-vae-ft-mse/diffusion_pytorch_model.bin
2024-10-09 05:31:51,759 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/sd-vae-ft-mse/diffusion_pytorch_model.safetensors
2024-10-09 05:31:51,761 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/sd-vae-ft-mse/config.json
2024-10-09 05:31:53,160 - loader - INFO -     ✅ Downloaded sd-vae-ft-mse/config.json
2024-10-09 05:31:58,040 - loader - INFO -     ✅ Downloaded liveportrait/stitching_retargeting_module.pth
2024-10-09 05:31:58,405 - loader - INFO -     ✅ Downloaded liveportrait/appearance_feature_extractor.pth
2024-10-09 05:32:03,873 - loader - INFO -     ✅ Downloaded insightface/buffalo_l/2d106det.onnx
2024-10-09 05:32:10,918 - loader - INFO -     ✅ Downloaded insightface/buffalo_l/det_10g.onnx
2024-10-09 05:33:47,124 - loader - INFO -     ✅ Downloaded liveportrait/motion_extractor.pth
2024-10-09 05:33:49,321 - loader - INFO -     ✅ Downloaded face-detector/s3fd-619a316812.pth
2024-10-09 05:34:14,391 - loader - INFO -     ✅ Downloaded liveportrait/landmark.onnx
2024-10-09 05:34:55,393 - loader - INFO -     ✅ Downloaded liveportrait/spade_generator.pth
2024-10-09 05:35:00,544 - loader - INFO -     ✅ Downloaded liveportrait/warping_module.pth
2024-10-09 05:35:35,501 - loader - INFO -     ✅ Downloaded insightface/models/buffalo_l.zip
2024-10-09 05:35:50,633 - loader - INFO -     ✅ Downloaded sd-vae-ft-mse/diffusion_pytorch_model.safetensors
2024-10-09 05:35:56,530 - loader - INFO -     ✅ Downloaded sd-vae-ft-mse/diffusion_pytorch_model.bin
2024-10-09 05:36:14,246 - loader - INFO -     ✅ Downloaded dwpose/dw-ll_ucoco_384.pth
2024-10-09 05:36:14,246 - loader - INFO -   ✅ All models are available
2024-10-09 05:36:15,708 - loader - INFO -   ⏳ Loading LivePortrait models...
2024-10-09 05:36:15,719 - __main__ - ERROR - 🚨 Error during application initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
2024-10-09 05:36:15,719 - __main__ - ERROR - Full traceback:
Traceback (most recent call last):
  File "/home/user/app/app.py", line 114, in initialize_app
    live_portrait = await initialize_models()
  File "/home/user/app/loader.py", line 157, in initialize_models
    live_portrait = await loader.load_live_portrait()
  File "/home/user/app/loader.py", line 131, in load_live_portrait
    live_portrait_pipeline = await asyncio.to_thread(
  File "/usr/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/app/liveportrait/live_portrait_pipeline.py", line 38, in __init__
    self.live_portrait_wrapper: LivePortraitWrapper = LivePortraitWrapper(cfg=inference_cfg)
  File "/home/user/app/liveportrait/live_portrait_wrapper.py", line 28, in __init__
    self.appearance_feature_extractor = load_model(cfg.checkpoint_F, model_config, cfg.device_id, 'appearance_feature_extractor')
  File "/home/user/app/liveportrait/utils/helper.py", line 97, in load_model
    model = AppearanceFeatureExtractor(**model_params).cuda(device)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 916, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 805, in _apply
    param_applied = fn(param)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 916, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/user/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 314, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
2024-10-09 05:36:15,720 - __main__ - CRITICAL - 🚨 FATAL: Failed to start the app: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
2024-10-09 05:36:15,720 - __main__ - ERROR - Full traceback:
Traceback (most recent call last):
  File "/home/user/app/app.py", line 140, in <module>
    app = asyncio.run(initialize_app())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/user/app/app.py", line 114, in initialize_app
    live_portrait = await initialize_models()
  File "/home/user/app/loader.py", line 157, in initialize_models
    live_portrait = await loader.load_live_portrait()
  File "/home/user/app/loader.py", line 131, in load_live_portrait
    live_portrait_pipeline = await asyncio.to_thread(
  File "/usr/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/app/liveportrait/live_portrait_pipeline.py", line 38, in __init__
    self.live_portrait_wrapper: LivePortraitWrapper = LivePortraitWrapper(cfg=inference_cfg)
  File "/home/user/app/liveportrait/live_portrait_wrapper.py", line 28, in __init__
    self.appearance_feature_extractor = load_model(cfg.checkpoint_F, model_config, cfg.device_id, 'appearance_feature_extractor')
  File "/home/user/app/liveportrait/utils/helper.py", line 97, in load_model
    model = AppearanceFeatureExtractor(**model_params).cuda(device)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 916, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 805, in _apply
    param_applied = fn(param)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 916, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/user/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 314, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
2024-10-09 05:36:16,072 - httpx - INFO - HTTP Request: GET https://api.gradio.app/gradio-messaging/en "HTTP/1.1 200 OK"

**Comment by dotNet-Spider** [comment]
Login to your WSL2 Linux machine and check if this command shows you your's GPU.

`nvidia-smi`

Maybe you are missing packages in your WSL2 Linux:

- CUDA Toolkit  
https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=deb_local

- NVIDIA Container Toolkit 
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installing-the-nvidia-container-toolkit

and then run like 

`docker run -p 8080:8080 --runtime=nvidia --gpus all facepoke`

**Comment by tiandaoyuxi** [comment]
(base) D:\FacePoke>docker run -p 8080:8080 --runtime=nvidia --gpus all facepoke

==========
== CUDA ==
==========

CUDA Version 12.4.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

2024-10-09 09:28:06,225 - loader - INFO - 🚀 Setting up storage directories...
2024-10-09 09:28:06,225 - loader - INFO -   Directory created: /tmp/data/models
2024-10-09 09:28:06,225 - loader - INFO - ✅ Storage directories setup completed.
2024-10-09 09:28:06,306 - __main__ - INFO - Starting FacePoke application
2024-10-09 09:28:06,306 - __main__ - INFO - Initializing application...
2024-10-09 09:28:06,306 - loader - INFO - 🚀 Starting model initialization...
2024-10-09 09:28:06,306 - loader - INFO -   🔎 Looking for models...
2024-10-09 09:28:06,307 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/dwpose/dw-ll_ucoco_384.pth
2024-10-09 09:28:06,308 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/face-detector/s3fd-619a316812.pth
2024-10-09 09:28:06,308 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/liveportrait/spade_generator.pth
2024-10-09 09:28:06,310 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/liveportrait/warping_module.pth
2024-10-09 09:28:06,311 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/liveportrait/motion_extractor.pth
2024-10-09 09:28:06,312 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/liveportrait/stitching_retargeting_module.pth
2024-10-09 09:28:06,314 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/liveportrait/appearance_feature_extractor.pth
2024-10-09 09:28:06,315 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/liveportrait/landmark.onnx
2024-10-09 09:28:06,317 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/insightface/models/buffalo_l.zip
2024-10-09 09:28:06,317 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/insightface/buffalo_l/det_10g.onnx
2024-10-09 09:28:06,319 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/insightface/buffalo_l/2d106det.onnx
2024-10-09 09:28:06,320 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/sd-vae-ft-mse/diffusion_pytorch_model.bin
2024-10-09 09:28:06,320 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/sd-vae-ft-mse/diffusion_pytorch_model.safetensors
2024-10-09 09:28:06,322 - loader - INFO -     ⏳ Downloading jbilcke-hf/model-cocktail/sd-vae-ft-mse/config.json
2024-10-09 09:28:07,984 - loader - INFO -     ✅ Downloaded sd-vae-ft-mse/config.json
2024-10-09 09:28:13,380 - loader - INFO -     ✅ Downloaded liveportrait/stitching_retargeting_module.pth
2024-10-09 09:28:13,578 - loader - INFO -     ✅ Downloaded liveportrait/appearance_feature_extractor.pth
2024-10-09 09:28:15,325 - loader - INFO -     ✅ Downloaded insightface/buffalo_l/2d106det.onnx
2024-10-09 09:28:23,065 - loader - INFO -     ✅ Downloaded insightface/buffalo_l/det_10g.onnx
2024-10-09 09:29:30,087 - loader - INFO -     ✅ Downloaded face-detector/s3fd-619a316812.pth
2024-10-09 09:29:59,366 - loader - INFO -     ✅ Downloaded liveportrait/motion_extractor.pth
2024-10-09 09:30:03,983 - loader - INFO -     ✅ Downloaded liveportrait/landmark.onnx
2024-10-09 09:30:49,299 - loader - INFO -     ✅ Downloaded liveportrait/warping_module.pth
2024-10-09 09:31:09,398 - loader - INFO -     ✅ Downloaded liveportrait/spade_generator.pth
2024-10-09 09:31:24,788 - loader - INFO -     ✅ Downloaded insightface/models/buffalo_l.zip
2024-10-09 09:31:39,513 - loader - INFO -     ✅ Downloaded sd-vae-ft-mse/diffusion_pytorch_model.bin
2024-10-09 09:31:44,461 - loader - INFO -     ✅ Downloaded sd-vae-ft-mse/diffusion_pytorch_model.safetensors
2024-10-09 09:32:01,884 - loader - INFO -     ✅ Downloaded dwpose/dw-ll_ucoco_384.pth
2024-10-09 09:32:01,884 - loader - INFO -   ✅ All models are available
2024-10-09 09:32:03,351 - loader - INFO -   ⏳ Loading LivePortrait models...
2024-10-09 09:32:03,921 - httpx - INFO - HTTP Request: GET https://api.gradio.app/gradio-messaging/en "HTTP/1.1 200 OK"
download_path: /tmp/data/models/insightface/models/buffalo_l
Downloading /tmp/data/models/insightface/models/buffalo_l.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip...
100%|██████████| 281857/281857 [01:08<00:00, 4093.61KB/s]
2024-10-09 09:33:22,372 - loader - INFO -   ✅ LivePortrait models loaded successfully.
2024-10-09 09:33:22,372 - loader - INFO - ✅ Model initialization completed.
2024-10-09 09:33:22,372 - __main__ - INFO - 🚀 Creating Engine instance...
2024-10-09 09:33:22,372 - engine - INFO - ✅ FacePoke Engine initialized successfully.
2024-10-09 09:33:22,372 - __main__ - INFO - ✅ Engine instance created.
2024-10-09 09:33:22,372 - __main__ - INFO - Application routes configured
2024-10-09 09:33:22,374 - __main__ - INFO - Application initialized, starting web server
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
2024-10-09 09:35:06,661 - aiohttp.access - INFO - 172.17.0.1 [09/Oct/2024:09:35:06 +0000] "GET / HTTP/1.1" 200 488 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
2024-10-09 09:35:06,669 - aiohttp.access - INFO - 172.17.0.1 [09/Oct/2024:09:35:06 +0000] "GET /index.js HTTP/1.1" 200 1295919 "http://127.0.0.1:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
2024-10-09 09:35:06,863 - aiohttp.access - INFO - 172.17.0.1 [09/Oct/2024:09:35:06 +0000] "GET /hf-logo.svg HTTP/1.1" 200 4792 "http://127.0.0.1:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
2024-10-09 09:35:08,288 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01\x06\xb4\x01'
      ^
2024-10-09 09:35:08,288 - aiohttp.access - INFO - 172.17.0.1 [09/Oct/2024:09:35:08 +0000] "UNKNOWN / HTTP/1.0" 400 226 "-" "-"
2024-10-09 09:35:08,309 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01\x06\xd4\x01'
      ^
2024-10-09 09:35:08,309 - aiohttp.access - INFO - 172.17.0.1 [09/Oct/2024:09:35:08 +0000] "UNKNOWN / HTTP/1.0" 400 226 "-" "-"
2024-10-09 09:35:10,318 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01\x06\xb4\x01'
      ^
2024-10-09 09:35:10,319 - aiohttp.access - INFO - 172.17.0.1 [09/Oct/2024:09:35:10 +0000] "UNKNOWN / HTTP/1.0" 400 226 "-" "-"
2024-10-09 09:35:10,341 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01\x06\x94\x01'
      ^
2024-10-09 09:35:10,341 - aiohttp.access - INFO - 172.17.0.1 [09/Oct/2024:09:35:10 +0000] "UNKNOWN / HTTP/1.0" 400 226 "-" "-"
2024-10-09 09:35:14,354 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01\x06\xf4\x01'
      ^
2024-10-09 09:35:14,354 - aiohttp.access - INFO - 172.17.0.1 [09/Oct/2024:09:35:14 +0000] "UNKNOWN / HTTP/1.0" 400 226 "-" "-"
2024-10-09 09:35:14,382 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01\x06\xb4\x01'
      ^
2024-10-09 09:35:14,383 - aiohttp.access - INFO - 172.17.0.1 [09/Oct/2024:09:35:14 +0000] "UNKNOWN / HTTP/1.0" 400 226 "-" "-"
2024-10-09 09:35:22,390 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01\x06\x94\x01'
      ^
2024-10-09 09:35:22,390 - aiohttp.access - INFO - 172.17.0.1 [09/Oct/2024:09:35:22 +0000] "UNKNOWN / HTTP/1.0" 400 226 "-" "-"
2024-10-09 09:35:22,414 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01\x06\x94\x01'
      ^
2024-10-09 09:35:22,414 - aiohttp.access - INFO - 172.17.0.1 [09/Oct/2024:09:35:22 +0000] "UNKNOWN / HTTP/1.0" 400 226 "-" "-"
2024-10-09 09:35:38,421 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01\x06\xd4\x01'
      ^
2024-10-09 09:35:38,422 - aiohttp.access - INFO - 172.17.0.1 [09/Oct/2024:09:35:38 +0000] "UNKNOWN / HTTP/1.0" 400 226 "-" "-"
2024-10-09 09:35:38,442 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01\x06\x94\x01'
      ^
2024-10-09 09:35:38,442 - aiohttp.access - INFO - 172.17.0.1 [09/Oct/2024:09:35:38 +0000] "UNKNOWN / HTTP/1.0" 400 226 "-" "-"

**Comment by dotNet-Spider** [comment]
Yup, your issue is gone :) You can resolve it.

Now, you are facing issue from https://github.com/jbilcke-hf/FacePoke/issues/6 .

**Comment by tiandaoyuxi** [comment]
#6 is also me, it still doesn't work
