### ISSUE TITLE
OpenCV error

### ISSUE THREAD

**Issue by markliuyuxiang** [jbilcke-hf/FacePoke#15]
/root/FacePoke/liveportrait/utils/dependencies/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
2024-10-10 01:28:20,704 - __main__ - ERROR - Error in engine: Failed to modify image: OpenCV(4.8.1) /io/opencv/modules/imgproc/src/imgwarp.cpp:2729: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'warpAffine'

2024-10-10 01:28:20,704 - __main__ - ERROR - Full traceback:
Traceback (most recent call last):
  File "/root/FacePoke/engine.py", line 191, in transform_image
    mask_ori = await asyncio.to_thread(prepare_paste_back,
  File "/root/miniconda3/envs/facepoke/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/root/miniconda3/envs/facepoke/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/FacePoke/liveportrait/utils/crop.py", line 402, in prepare_paste_back
    mask_ori = _transform_img(mask_crop, crop_M_c2o, dsize)
  File "/root/FacePoke/liveportrait/utils/crop.py", line 33, in _transform_img
    return cv2.warpAffine(img, M[:2, :], dsize=_dsize, flags=flags)
cv2.error: OpenCV(4.8.1) /io/opencv/modules/imgproc/src/imgwarp.cpp:2729: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'warpAffine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/FacePoke/app.py", line 82, in websocket_handler
    webp_bytes = await engine.transform_image(data.get('uuid'), data.get('params'))
  File "/root/FacePoke/engine.py", line 210, in transform_image
    raise ValueError(f"Failed to modify image: {str(e)}")
ValueError: Failed to modify image: OpenCV(4.8.1) /io/opencv/modules/imgproc/src/imgwarp.cpp:2729: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'warpAffine'

**Comment by n0012** [comment]
I have the same error.  Running with  Docker.

**Comment by Phate334** [comment]
here will read this png file

```python
def prepare_paste_back(mask_crop, crop_M_c2o, dsize):
    """prepare mask for later image paste back
    """
    if mask_crop is None:
        mask_crop = cv2.imread(make_abs_path('./resources/mask_template.png'), cv2.IMREAD_COLOR)
    mask_ori = _transform_img(mask_crop, crop_M_c2o, dsize)
    mask_ori = mask_ori.astype(np.float32) / 255.
    return mask_ori
```

https://github.com/jbilcke-hf/FacePoke/blob/main/liveportrait/utils/resources/mask_template.png

The file is stored in Git LFS. Make sure all content has been pulled before building the Docker image.

```bash
$ sudo apt install git-lfs
$ git lfs install 
$ git lfs pull
# and rebuild image again
$ docker build -t facepoke .
```

**Comment by n0012** [comment]
fixed for me.  thanks!

**Comment by jbilcke-hf** [comment]
Hello @Phate334  and @n0012 

Sorry about that, that's a good point - I've just updated the README.md to reflect this:

https://github.com/jbilcke-hf/FacePoke/commit/6752d4fb2523a57e931ee0822af4e2c34b06cbda
