### ISSUE TITLE
about：ValueError: could not broadcast input array from shape (512,512,4) into shape (512,512,3)

### ISSUE THREAD

**Issue by tiandaoyuxi** [jbilcke-hf/FacePoke#16]
Some images can be control while others cannot.

In this context:
(512, 512, 4) refers to an image with 4 channels (RGBA: Red, Green, Blue, and Alpha/transparency).
(512, 512, 3) refers to an image with 3 channels (RGB: Red, Green, and Blue).
The function expects an RGB image, but it's receiving an RGBA image. To fix this issue, you need to convert the RGBA image to an RGB image by

But I couldn't handle the Alpha channel properly even when I used PS to remove it.
Does it have any special requirements for the material images.

2024-10-10 10:05:43,771 - __main__ - ERROR - Error in engine: could not broadcast input array from shape (512,512,4) into shape (512,512,3)
2024-10-10 10:05:43,771 - __main__ - ERROR - Full traceback:
Traceback (most recent call last):
  File "D:\FacePoke\app.py", line 76, in websocket_handler
    res = await engine.load_image(msg.data)
  File "C:\Users\win11\.conda\envs\facepoke\lib\site-packages\async_lru\__init__.py", line 294, in __call__
    return await self.__wrapper(self.__instance, *fn_args, **fn_kwargs)
  File "C:\Users\win11\.conda\envs\facepoke\lib\site-packages\async_lru\__init__.py", line 227, in __call__
    return await asyncio.shield(fut)
  File "D:\FacePoke\engine.py", line 73, in load_image
    crop_info = await asyncio.to_thread(self.live_portrait.cropper.crop_single_image, img_rgb)
  File "C:\Users\win11\.conda\envs\facepoke\lib\asyncio\threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "C:\Users\win11\.conda\envs\facepoke\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\FacePoke\liveportrait\utils\cropper.py", line 73, in crop_single_image
    src_face = self.face_analysis_wrapper.get(
  File "D:\FacePoke\liveportrait\utils\face_analysis_diy.py", line 47, in get
    bboxes, kpss = self.det_model.detect(img_bgr, max_num=max_num, metric='default')
  File "D:\FacePoke\liveportrait\utils\dependencies\insightface\model_zoo\retinaface.py", line 222, in detect
    det_img[:new_height, :new_width, :] = resized_img
ValueError: could not broadcast input array from shape (512,512,4) into shape (512,512,3)

**Comment by tiandaoyuxi** [comment]
![lian](https://github.com/user-attachments/assets/401a34be-8ee0-4012-9ced-47ff317efe87)

**Comment by Phate334** [comment]
try use jpg

**Comment by tiandaoyuxi** [comment]
> try use jpg

Cool, jpg is work. Thx!
