### ISSUE TITLE
Error in engine: Failed to modify image: OpenCV(4.8.1)

### ISSUE THREAD

**Issue by mn8821236** [jbilcke-hf/FacePoke#20]
E:\facepoke\FacePoke-main\liveportrait\utils\dependencies\insightface\utils\transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
2024-10-11 00:16:37,801 - __main__ - ERROR - Error in engine: Failed to modify image: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:2729: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'cv::warpAffine'

2024-10-11 00:16:37,802 - __main__ - ERROR - Full traceback:
Traceback (most recent call last):
  File "E:\facepoke\FacePoke-main\engine.py", line 191, in transform_image
    mask_ori = await asyncio.to_thread(prepare_paste_back,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\facepoke\FacePoke-main\liveportrait\utils\crop.py", line 402, in prepare_paste_back
    mask_ori = _transform_img(mask_crop, crop_M_c2o, dsize)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\facepoke\FacePoke-main\liveportrait\utils\crop.py", line 33, in _transform_img
    return cv2.warpAffine(img, M[:2, :], dsize=_dsize, flags=flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:2729: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'cv::warpAffine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\facepoke\FacePoke-main\app.py", line 82, in websocket_handler
    webp_bytes = await engine.transform_image(data.get('uuid'), data.get('params'))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\facepoke\FacePoke-main\engine.py", line 210, in transform_image
    raise ValueError(f"Failed to modify image: {str(e)}")
ValueError: Failed to modify image: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:2729: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'cv::warpAffine'

2024-10-11 00:16:37,888 - __main__ - ERROR - Error in engine: Failed to modify image: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:2729: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'cv::warpAffine'

2024-10-11 00:16:37,888 - __main__ - ERROR - Full traceback:
Traceback (most recent call last):
  File "E:\facepoke\FacePoke-main\engine.py", line 191, in transform_image
    mask_ori = await asyncio.to_thread(prepare_paste_back,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\facepoke\FacePoke-main\liveportrait\utils\crop.py", line 402, in prepare_paste_back
    mask_ori = _transform_img(mask_crop, crop_M_c2o, dsize)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\facepoke\FacePoke-main\liveportrait\utils\crop.py", line 33, in _transform_img
    return cv2.warpAffine(img, M[:2, :], dsize=_dsize, flags=flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:2729: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'cv::warpAffine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\facepoke\FacePoke-main\app.py", line 82, in websocket_handler
    webp_bytes = await engine.transform_image(data.get('uuid'), data.get('params'))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\facepoke\FacePoke-main\engine.py", line 210, in transform_image
    raise ValueError(f"Failed to modify image: {str(e)}")
ValueError: Failed to modify image: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:2729: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'cv::warpAffine'

![6193c228eadb82588](https://github.com/user-attachments/assets/481adc43-06c7-4543-8b61-601af4f8e7b5)

**Comment by mn8821236** [comment]
The issue has been fixed because the resource file ‘mask_template.png’ in the downloaded code was problematic. I resolved it by re-downloading the file from the repository and replacing it

**Comment by Phate334** [comment]
https://github.com/jbilcke-hf/FacePoke/issues/15#issuecomment-2405215583

just pull all contents from git lfs.

**Comment by jbilcke** [comment]
hello, thanks for pointing this, the README.md has been updated to mention the usage of git lfs:
https://github.com/jbilcke-hf/FacePoke/commit/6752d4fb2523a57e931ee0822af4e2c34b06cbda

**Comment by mn8821236** [comment]
> > The issue has been fixed because the resource file ‘mask_template.png’ in the downloaded code was problematic. I resolved it by re-downloading the file from the repository and replacing it
> 
> in what folder

"liveportrait/utils/resources/mask_template.png"
