### ISSUE TITLE
Failed to start the app: DLL load failed while importing onnx_cpp2py_export

### ISSUE THREAD

**Issue by kornuolis2** [jbilcke-hf/FacePoke#23]
Receive this error during app.py launch:

2024-10-15 15:04:24,697 - loader - INFO - 🚀 Setting up storage directories...
2024-10-15 15:04:24,697 - loader - INFO -   Directory already exists: /tmp/data\models
2024-10-15 15:04:24,697 - loader - INFO - ✅ Storage directories setup completed.
2024-10-15 15:04:24,865 - __main__ - INFO - Starting FacePoke application
2024-10-15 15:04:24,865 - __main__ - INFO - Initializing application...
2024-10-15 15:04:24,865 - loader - INFO - 🚀 Starting model initialization...
2024-10-15 15:04:24,865 - loader - INFO -   🔎 Looking for models...
2024-10-15 15:04:24,867 - loader - INFO -   ✅ All models are available
2024-10-15 15:04:27,208 - httpx - INFO - HTTP Request: GET https://api.gradio.app/gradio-messaging/en "HTTP/1.1 200 OK"
2024-10-15 15:04:28,224 - __main__ - ERROR - 🚨 Error during application initialization: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.
2024-10-15 15:04:28,224 - __main__ - ERROR - Full traceback:
Traceback (most recent call last):
  File "E:\SD2\FacePoke\app.py", line 114, in initialize_app
    live_portrait = await initialize_models()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SD2\FacePoke\loader.py", line 157, in initialize_models
    live_portrait = await loader.load_live_portrait()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SD2\FacePoke\loader.py", line 128, in load_live_portrait
    from liveportrait.live_portrait_pipeline import LivePortraitPipeline
  File "E:\SD2\FacePoke\liveportrait\live_portrait_pipeline.py", line 20, in <module>
    from .utils.cropper import Cropper
  File "E:\SD2\FacePoke\liveportrait\utils\cropper.py", line 12, in <module>
    from .face_analysis_diy import FaceAnalysisDIY
  File "E:\SD2\FacePoke\liveportrait\utils\face_analysis_diy.py", line 9, in <module>
    from .dependencies.insightface.app import FaceAnalysis
  File "E:\SD2\FacePoke\liveportrait\utils\dependencies\insightface\__init__.py", line 16, in <module>
    from . import model_zoo
  File "E:\SD2\FacePoke\liveportrait\utils\dependencies\insightface\model_zoo\__init__.py", line 1, in <module>
    from .model_zoo import get_model
  File "E:\SD2\FacePoke\liveportrait\utils\dependencies\insightface\model_zoo\model_zoo.py", line 11, in <module>
    from .arcface_onnx import *
  File "E:\SD2\FacePoke\liveportrait\utils\dependencies\insightface\model_zoo\arcface_onnx.py", line 10, in <module>
    import onnx
  File "E:\SD2\FacePoke\.venv\Lib\site-packages\onnx\__init__.py", line 77, in <module>
    from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.
2024-10-15 15:04:28,228 - __main__ - CRITICAL - 🚨 FATAL: Failed to start the app: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.
2024-10-15 15:04:28,228 - __main__ - ERROR - Full traceback:
Traceback (most recent call last):
  File "E:\SD2\FacePoke\app.py", line 140, in <module>
    app = asyncio.run(initialize_app())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZerotuL\anaconda3\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\ZerotuL\anaconda3\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZerotuL\anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\SD2\FacePoke\app.py", line 114, in initialize_app
    live_portrait = await initialize_models()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SD2\FacePoke\loader.py", line 157, in initialize_models
    live_portrait = await loader.load_live_portrait()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SD2\FacePoke\loader.py", line 128, in load_live_portrait
    from liveportrait.live_portrait_pipeline import LivePortraitPipeline
  File "E:\SD2\FacePoke\liveportrait\live_portrait_pipeline.py", line 20, in <module>
    from .utils.cropper import Cropper
  File "E:\SD2\FacePoke\liveportrait\utils\cropper.py", line 12, in <module>
    from .face_analysis_diy import FaceAnalysisDIY
  File "E:\SD2\FacePoke\liveportrait\utils\face_analysis_diy.py", line 9, in <module>
    from .dependencies.insightface.app import FaceAnalysis
  File "E:\SD2\FacePoke\liveportrait\utils\dependencies\insightface\__init__.py", line 16, in <module>
    from . import model_zoo
  File "E:\SD2\FacePoke\liveportrait\utils\dependencies\insightface\model_zoo\__init__.py", line 1, in <module>
    from .model_zoo import get_model
  File "E:\SD2\FacePoke\liveportrait\utils\dependencies\insightface\model_zoo\model_zoo.py", line 11, in <module>
    from .arcface_onnx import *
  File "E:\SD2\FacePoke\liveportrait\utils\dependencies\insightface\model_zoo\arcface_onnx.py", line 10, in <module>
    import onnx
  File "E:\SD2\FacePoke\.venv\Lib\site-packages\onnx\__init__.py", line 77, in <module>
    from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.

**Comment by jbilcke-hf** [comment]
@kornuolis2 can you try to edit the `requirements.txt`,

then locate this line:

```
onnx==1.16.2
```

replace it by this:

```
onnx==1.16.1
```

and try to install the dependencies again?

For some context, I think that is due to this: https://github.com/onnx/onnx/issues/6267

**Comment by kornuolis2** [comment]
@jbilcke-hf Worked like a charm, ty

**Comment by jbilcke-hf** [comment]
cool! I will make it default then 😃
