### ISSUE TITLE
During handling of the above exception, another exception occurred:

### ISSUE THREAD

**Issue by zachysaur** [jbilcke-hf/FacePoke#25]
2024-10-23 14:59:18,546 - loader - INFO -   ✅ LivePortrait models loaded successfully.
2024-10-23 14:59:18,546 - loader - INFO - ✅ Model initialization completed.
2024-10-23 14:59:18,547 - __main__ - INFO - 🚀 Creating Engine instance...
2024-10-23 14:59:18,547 - engine - INFO - ✅ FacePoke Engine initialized successfully.
2024-10-23 14:59:18,548 - __main__ - INFO - ✅ Engine instance created.
2024-10-23 14:59:18,549 - __main__ - INFO - Application routes configured
2024-10-23 14:59:18,550 - __main__ - INFO - Application initialized, starting web server
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
2024-10-23 14:59:29,117 - aiohttp.access - INFO - 127.0.0.1 [23/Oct/2024:14:59:29 +0500] "GET / HTTP/1.1" 200 488 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"
2024-10-23 14:59:29,134 - aiohttp.access - INFO - 127.0.0.1 [23/Oct/2024:14:59:29 +0500] "GET /index.js HTTP/1.1" 200 1302203 "http://127.0.0.1:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"
2024-10-23 14:59:29,528 - aiohttp.access - INFO - 127.0.0.1 [23/Oct/2024:14:59:29 +0500] "GET /hf-logo.svg HTTP/1.1" 200 4792 "http://127.0.0.1:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"
F:\New folder (2)\FacePoke-main\liveportrait\utils\dependencies\insightface\utils\transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
2024-10-23 14:59:40,627 - __main__ - ERROR - Error in engine: Failed to modify image: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:2825: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'cv::warpAffine'

2024-10-23 14:59:40,628 - __main__ - ERROR - Full traceback:
Traceback (most recent call last):
  File "F:\New folder (2)\FacePoke-main\engine.py", line 209, in transform_image
    mask_ori = await asyncio.to_thread(prepare_paste_back,
  File "C:\Users\ggrov\AppData\Local\Programs\Python\Python310\lib\asyncio\threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "C:\Users\ggrov\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\New folder (2)\FacePoke-main\liveportrait\utils\crop.py", line 402, in prepare_paste_back
    mask_ori = _transform_img(mask_crop, crop_M_c2o, dsize)
  File "F:\New folder (2)\FacePoke-main\liveportrait\utils\crop.py", line 33, in _transform_img
    return cv2.warpAffine(img, M[:2, :], dsize=_dsize, flags=flags)
cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:2825: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'cv::warpAffine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\New folder (2)\FacePoke-main\app.py", line 82, in websocket_handler
    webp_bytes = await engine.transform_image(data.get('uuid'), data.get('params'))
  File "F:\New folder (2)\FacePoke-main\engine.py", line 228, in transform_image
    raise ValueError(f"Failed to modify image: {str(e)}")
ValueError: Failed to modify image: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:2825: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'cv::warpAffine'

**Comment by irellik** [comment]
I had the same problem.

**Comment by irellik** [comment]
This project require KwaiVGI/LivePortrait, But the code in the liveportrait folder has some problems. Get the latest code from [KwaiVGI/LivePortrait](https://github.com/KwaiVGI/LivePortrait) and make some adjustments to it will work normally.

**Comment by lou34673723** [comment]
Yes, this is not working for me either. Same errors.

**Comment by andi8086** [comment]
I have the same problem. No idea what's going on. Please fix this!!

**Comment by lou34673723** [comment]
Just to update: I deleted my local clone of this project and completely rebuilt it; and it works now. I had been trying to use a workaround version of gradio since 5.0.0b4 wasn't available. The latest update has solved this issue.
