### ISSUE TITLE
Error with Image

### ISSUE THREAD

**Issue by Cheety** [jbilcke-hf/FacePoke#30]
any idea what's wrong? i get this after image upload

` __main__ - ERROR - Error in engine: Failed to modify image: OpenCV(4.8.1) /io/opencv/modules/imgproc/src/imgwarp.cpp:2729: error: (-215:Assertion failed) src.cols >0 && src.rows > 0 in function 'warpAffine'

2024-11-23 23:47:44,251 - __main__ - ERROR - Full traceback:
Traceback (most recent call last):
  File "/workspace/FacePoke/engine.py", line 209, in transform_image
    mask_ori = await asyncio.to_thread(prepare_paste_back,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/FacePoke/liveportrait/utils/crop.py", line 402, in prepare_paste_back
    mask_ori = _transform_img(mask_crop, crop_M_c2o, dsize)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/FacePoke/liveportrait/utils/crop.py", line 33, in _transform_img
    return cv2.warpAffine(img, M[:2, :], dsize=_dsize, flags=flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

**Comment by Sakurajima-Pang** [comment]
I have a similar problem
`cv2.error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:2729: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'cv::warpAffine'`

**Comment by Sakurajima-Pang** [comment]
I use the integration package made by others (the environment and dependencies are packaged), which can only identify objects, but cannot be modified. At the same time, the same error is reported. Maybe our hardware has some problems. I use gtx1650, CUDA12.7、cuda12.6，torch2.5.1-cu12.4-cp310
`FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4`

**Comment by hippalectryon-0** [comment]
The reason for this is that `git lfs` is not properly configured, and you are missing https://github.com/jbilcke-hf/FacePoke/blob/main/liveportrait/utils/resources/mask_template.png. Simply download it manually and it should work fine.
