### ISSUE TITLE
win11 help!

### ISSUE THREAD

**Issue by tiandaoyuxi** [jbilcke-hf/FacePoke#6]
2024-10-08 12:00:44,306 - aiohttp.access - INFO - 127.0.0.1 [08/Oct/2024:12:00:44 +0800] "UNKNOWN / HTTP/1.0" 400 248 "-" "-"
2024-10-08 12:00:52,310 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "D:\FacePoke\venv\Lib\site-packages\aiohttp\web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp\\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    bytearray(b'\x16\x03\x01\x06\xd4\x01')
                 ^
2024-10-08 12:00:52,310 - aiohttp.access - INFO - 127.0.0.1 [08/Oct/2024:12:00:52 +0800] "UNKNOWN / HTTP/1.0" 400 248 "-" "-"
2024-10-08 12:00:52,328 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "D:\FacePoke\venv\Lib\site-packages\aiohttp\web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp\\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    bytearray(b'\x16\x03\x01\x06\xf4\x01')
                 ^
2024-10-08 12:00:52,329 - aiohttp.access - INFO - 127.0.0.1 [08/Oct/2024:12:00:52 +0800] "UNKNOWN / HTTP/1.0" 400 248 "-" "-"
2024-10-08 12:01:08,356 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "D:\FacePoke\venv\Lib\site-packages\aiohttp\web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp\\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    bytearray(b'\x16\x03\x01\x06\x94\x01')
                 ^
2024-10-08 12:01:08,356 - aiohttp.access - INFO - 127.0.0.1 [08/Oct/2024:12:01:08 +0800] "UNKNOWN / HTTP/1.0" 400 248 "-" "-"
2024-10-08 12:01:08,370 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "D:\FacePoke\venv\Lib\site-packages\aiohttp\web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp\\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    bytearray(b'\x16\x03\x01\x06\xb4\x01')
                 ^
2024-10-08 12:01:08,371 - aiohttp.access - INFO - 127.0.0.1 [08/Oct/2024:12:01:08 +0800] "UNKNOWN / HTTP/1.0" 400 248 "-" "-"

**Comment by tiandaoyuxi** [comment]
const connect = () => {
     this.ws = new WebSocket(ws://${window.location.host}/ws);
  /**
   *this.ws = new WebSocket(`wss://${window.location.host}/ws`);
   */ 
Same an error

**Comment by FlowDownTheRiver** [comment]
confirming it on windows 10 that it is not working and giving that error the other guys mentioned. needs a fix.

**Comment by tiandaoyuxi** [comment]
Thx，Patiently waiting for better progress.

**Comment by FlowDownTheRiver** [comment]
I have a suspicion that the requests to local server is made wrongly. Maybe it is related to : https , http . Not sure.

**Comment by threelum** [comment]
Hi, almost same error message on win10. 
I can open the page, import an image, facial markers are recognized, but no facial movements occur. 
ThanX

`Microsoft Windows [Version 10.0.19045.4894]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

(facepoke) C:\AI\FACEPOKE>python app.py
2024-10-08 22:14:55,927 - loader - INFO - ?? Setting up storage directories...
2024-10-08 22:14:55,927 - loader - INFO -   Directory already exists: /tmp/data\models
2024-10-08 22:14:55,928 - loader - INFO - ? Storage directories setup completed.
2024-10-08 22:14:56,117 - __main__ - INFO - Starting FacePoke application
2024-10-08 22:14:56,118 - __main__ - INFO - Initializing application...
2024-10-08 22:14:56,118 - loader - INFO - ?? Starting model initialization...
2024-10-08 22:14:56,118 - loader - INFO -   ?? Looking for models...
2024-10-08 22:14:56,121 - loader - INFO -   ? All models are available
2024-10-08 22:14:58,750 - httpx - INFO - HTTP Request: GET https://api.gradio.app/gradio-messaging/en "HTTP/1.1 200 OK"
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
2024-10-08 22:15:29,266 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "C:\Users\AUDIO\miniconda3\envs\facepoke\lib\site-packages\aiohttp\web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    bytearray(b'\x16\x03\x01\x06\xa6\x01')
                 ^
2024-10-08 22:15:29,268 - asyncio - ERROR - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\AUDIO\miniconda3\envs\facepoke\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\AUDIO\miniconda3\envs\facepoke\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
2024-10-08 22:15:29,570 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "C:\Users\AUDIO\miniconda3\envs\facepoke\lib\site-packages\aiohttp\web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    bytearray(b'\x16\x03\x01\x07\x06\x01')
                 ^
2024-10-08 22:15:29,571 - asyncio - ERROR - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\AUDIO\miniconda3\envs\facepoke\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\AUDIO\miniconda3\envs\facepoke\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
2024-10-08 22:15:31,887 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "C:\Users\AUDIO\miniconda3\envs\facepoke\lib\site-packages\aiohttp\web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    bytearray(b'\x16\x03\x01\x06\xc6\x01')
                 ^
2024-10-08 22:15:31,888 - asyncio - ERROR - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\AUDIO\miniconda3\envs\facepoke\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\AUDIO\miniconda3\envs\facepoke\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
2024-10-08 22:15:32,204 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "C:\Users\AUDIO\miniconda3\envs\facepoke\lib\site-packages\aiohttp\web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    bytearray(b'\x16\x03\x01\x06\xc6\x01')
                 ^
2024-10-08 22:15:32,205 - asyncio - ERROR - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\AUDIO\miniconda3\envs\facepoke\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\AUDIO\miniconda3\envs\facepoke\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
2024-10-08 22:15:36,520 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "C:\Users\AUDIO\miniconda3\envs\facepoke\lib\site-packages\aiohttp\web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    bytearray(b'\x16\x03\x01\x06\xc6\x01')
                 ^
2024-10-08 22:15:36,521 - asyncio - ERROR - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\AUDIO\miniconda3\envs\facepoke\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\AUDIO\miniconda3\envs\facepoke\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
2024-10-08 22:15:36,836 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "C:\Users\AUDIO\miniconda3\envs\facepoke\lib\site-packages\aiohttp\web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    bytearray(b'\x16\x03\x01\x07\x06\x01')
                 ^
2024-10-08 22:15:36,837 - asyncio - ERROR - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\AUDIO\miniconda3\envs\facepoke\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\AUDIO\miniconda3\envs\facepoke\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
2024-10-08 22:15:45,142 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "C:\Users\AUDIO\miniconda3\envs\facepoke\lib\site-packages\aiohttp\web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    bytearray(b'\x16\x03\x01\x06\xc6\x01')
                 ^
2024-10-08 22:15:45,142 - asyncio - ERROR - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\AUDIO\miniconda3\envs\facepoke\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\AUDIO\miniconda3\envs\facepoke\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
2024-10-08 22:15:45,444 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "C:\Users\AUDIO\miniconda3\envs\facepoke\lib\site-packages\aiohttp\web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    bytearray(b'\x16\x03\x01\x06\xc6\x01')
                 ^
2024-10-08 22:15:45,445 - asyncio - ERROR - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\AUDIO\miniconda3\envs\facepoke\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\AUDIO\miniconda3\envs\facepoke\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
`

**Comment by a1ex90** [comment]
Seems not to be windows specific. I have the same issue on Ubuntu 22.

```File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01\x06\xb4\x01'
      ^
2024-10-09 09:57:28,106 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):

**Comment by jbilcke-hf** [comment]
thanks for pointing this out and thanks for the fix!

I will merge the pull request now 👍

**Comment by tiandaoyuxi** [comment]
I'll try git pull and get feedback later,Thx.

**Comment by tiandaoyuxi** [comment]
Cool, it's work. Waiting for more features, I see someone has already fork it.
