### ISSUE TITLE
about：docke install ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory

### ISSUE THREAD

**Issue by tiandaoyuxi** [jbilcke-hf/FacePoke#7]
C:\Users\win11>docker build -t facepoke .
[+] Building 0.1s (1/1) FINISHED                                                                   docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 2B                                                                                 0.0s
ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/jrkospu23159mmqz60zhm1lxk

**Comment by LucaPuddu** [comment]
You need to clone the repo first. Follow the first step ONLY of the "Local Setup":

> 1. Clone the repository:
>
> ```
> git clone https://github.com/jbilcke-hf/FacePoke.git
> cd FacePoke
> ```

**Comment by tiandaoyuxi** [comment]
> You need to clone the repo first. Follow the first step ONLY of the "Local Setup":
> 
> > 1. Clone the repository:
> > 
> > ```
> > git clone https://github.com/jbilcke-hf/FacePoke.git
> > cd FacePoke
> > ```

Thanks！

**Comment by tiandaoyuxi** [comment]
2024-10-09 04:59:11,370 - loader - INFO -     ✅ Downloaded dwpose/dw-ll_ucoco_384.pth
2024-10-09 04:59:11,370 - loader - INFO -   ✅ All models are available
2024-10-09 04:59:12,805 - loader - INFO -   ⏳ Loading LivePortrait models...
2024-10-09 04:59:12,815 - __main__ - ERROR - 🚨 Error during application initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
2024-10-09 04:59:12,815 - __main__ - ERROR - Full traceback:
Traceback (most recent call last):
  File "/home/user/app/app.py", line 114, in initialize_app
    live_portrait = await initialize_models()
  File "/home/user/app/loader.py", line 157, in initialize_models
    live_portrait = await loader.load_live_portrait()
  File "/home/user/app/loader.py", line 131, in load_live_portrait
    live_portrait_pipeline = await asyncio.to_thread(
  File "/usr/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/app/liveportrait/live_portrait_pipeline.py", line 38, in __init__
    self.live_portrait_wrapper: LivePortraitWrapper = LivePortraitWrapper(cfg=inference_cfg)
  File "/home/user/app/liveportrait/live_portrait_wrapper.py", line 28, in __init__
    self.appearance_feature_extractor = load_model(cfg.checkpoint_F, model_config, cfg.device_id, 'appearance_feature_extractor')
  File "/home/user/app/liveportrait/utils/helper.py", line 97, in load_model
    model = AppearanceFeatureExtractor(**model_params).cuda(device)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 916, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 805, in _apply
    param_applied = fn(param)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 916, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/user/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 314, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
2024-10-09 04:59:12,817 - __main__ - CRITICAL - 🚨 FATAL: Failed to start the app: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
2024-10-09 04:59:12,817 - __main__ - ERROR - Full traceback:
Traceback (most recent call last):
  File "/home/user/app/app.py", line 140, in <module>
    app = asyncio.run(initialize_app())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/user/app/app.py", line 114, in initialize_app
    live_portrait = await initialize_models()
  File "/home/user/app/loader.py", line 157, in initialize_models
    live_portrait = await loader.load_live_portrait()
  File "/home/user/app/loader.py", line 131, in load_live_portrait
    live_portrait_pipeline = await asyncio.to_thread(
  File "/usr/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/app/liveportrait/live_portrait_pipeline.py", line 38, in __init__
    self.live_portrait_wrapper: LivePortraitWrapper = LivePortraitWrapper(cfg=inference_cfg)
  File "/home/user/app/liveportrait/live_portrait_wrapper.py", line 28, in __init__
    self.appearance_feature_extractor = load_model(cfg.checkpoint_F, model_config, cfg.device_id, 'appearance_feature_extractor')
  File "/home/user/app/liveportrait/utils/helper.py", line 97, in load_model
    model = AppearanceFeatureExtractor(**model_params).cuda(device)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 916, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 805, in _apply
    param_applied = fn(param)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 916, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/user/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 314, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
2024-10-09 04:59:13,186 - httpx - INFO - HTTP Request: GET https://api.gradio.app/gradio-messaging/en "HTTP/1.1 200 OK"

D:\FacePoke>

**Comment by mp3pintyo** [comment]
Sane error on Windows 11 with Docker.

**Comment by dotNet-Spider** [comment]
@mp3pintyo 
For the Nvidia issue check https://github.com/jbilcke-hf/FacePoke/issues/12


@tiandaoyuxi 
Your main issue is resolved, yes? 
Could you close this issue?
